name: physical-geodesy
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.10.*
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - math
  - pandas
  - scikit-image
  - xarray
  - netcdf4
  # For stereonets
  - mplstereonet
  # Fatiando
  - pooch
  - verde
  - harmonica
  - choclo
